
#!/bin/bash
#$ -cwd
#$ -o sublogs/A00c_genome_prep_star.$JOB_ID
#$ -j y
#$ -N A00c_prep_star
#$ -l h_rt=24:00:00,h_data=8G,highp
#$ -pe shared 8
#$ -hold_jid A00a_genome_dl_index





echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "



# environment init ------------------—------------------—-----------------------

. /u/local/Modules/default/init/modules.sh # <--
module load anaconda3 # <--
conda activate snmCTseq # <--

export $(cat snmCT_parameters.env | grep -v '^#' | xargs) # <--



# star index ------------------—------------------—-----------------------------
# assumes 2x150 paired-end

STAR --runThreadN 8 \
--runMode genomeGenerate \
--genomeDir ${ref_dir}/STAR149 \
--genomeFastaFiles ${ref_fasta} \
--sjdbGTFfile ${ref_gtf} \
--sjdbOverhang 149





echo -e "\n\n'A00c_genome_prep_star' completed.\n\n"


echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `
echo " "
