
#!/bin/bash
#$ -cwd
#$ -o sublogs/A04e_samstat_DNA.$JOB_ID.$TASK_ID
#$ -j y
#$ -l h_rt=6:00:00,h_data=24G
#$ -N A04e_samstat_DNA
#$ -t 1-256
#$ -hold_jid_ad A04a_bismark




echo "Job $JOB_ID.$SGE_TASK_ID started on:   " `hostname -s`
echo "Job $JOB_ID.$SGE_TASK_ID started on:   " `date `
echo " "




# environment init ------------------—------------------—-----------------------

. /u/local/Modules/default/init/modules.sh # <--
module load anaconda3 # <--
conda activate snmCTseq # <--

export $(cat snmCT_parameters.env | grep -v '^#' | xargs) # <--

skip_complete=true # <-- for help with incomplete jobs




# extract target filepaths ------------------—------------------—---------------

# helper functions
query_metadat () {
  awk -F',' -v targetcol="$1" \
      'NR==1 {
                for (i=1;i<=NF;i++) {
                    if ($i==targetcol) {assayout=i; break} }
                print $assayout
              }
      NR>1 {
                print $assayout
            }' ${metadat_well}
}

# extract target wells, print values for log

batchnum=($(query_metadat "batchnum"))
nwells=${#batchnum[@]}

target_well_rows=()
for ((row=1; row<=nwells; row++))
do
    if [[ "${batchnum[$row]}" == "${SGE_TASK_ID}" ]]
    then
        target_well_rows+=($row)
    fi
done



# filepaths associated with target rows in well-level metadata -----------------

wellprefix=($(query_metadat "wellprefix"))
dir_well=($(query_metadat "A04a_dir_bismark"))


# samtools stats on each well in the batch ------------------—------------------

for row in ${target_well_rows[@]} 
do

    cd ${dir_proj}
    
    if [[ -s ${dir_well[$row]}/samstats_PE \
        && -s ${dir_well[$row]}/samstats_SE \
        && "$skip_complete"=="true" ]]
    then
        echo -e "samstats output for '${wellprefix[$row]}' already exists. skipping this well.'"
    else
    
        echo -e "\n\nprofiling .bams from '${wellprefix[$row]}'...\n\n"

        cd ${dir_well[$row]}
        
        # run samtools stats
        samtools stats PE_final.bam | grep '^SN' | cut -f 2,3 > samstats_PE
        samtools stats SE_final.bam | grep '^SN' | cut -f 2,3 > samstats_SE
            
    fi
done


echo -e "\n\n'A04e_samstats_DNA' completed.\n\n"



echo "Job $JOB_ID.$SGE_TASK_ID ended on:   " `hostname -s`
echo "Job $JOB_ID.$SGE_TASK_ID ended on:   " `date `
echo " "


