
# #!/bin/bash
# #$ -cwd
# #$ -o sublogs/A05d_starfilt_check.$JOB_ID
# #$ -j y
# #$ -l h_rt=1:00:00,h_data=8G
# #$ -N A05d_starfilt_check
# #$ -hold_jid A05c_starfilt



echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "





# environment init -------------------------------------------------------------

export $(cat snmCT_parameters.env | grep -v '^#' | xargs) # <--



# helper functions / extract target filepaths ----------------------------------

query_metadat () {
  awk -F',' -v targetcol="$1" \
      'NR==1 {
                for (i=1;i<=NF;i++) {
                    if ($i==targetcol) {assayout=i; break} }
                print $assayout
              } 
      NR>1 {
                print $assayout
            }' ${metadat_well}
}

check_filepaths_in_assay() {
    for file in $@
        do 
        if [[ ! -s ${file} ]]
            then
                echo "missing '${file}'"
            fi
        done
}

check_filepath_by_batch() {
target_array=($@)
batches_to_rerun=()
for ((target_batch=1; target_batch<=nbatches; target_batch++))
    do
        target_well_rows=()
        for ((row=1; row<=nwells; row++))
        do
            if [[ "${batchnum[$row]}" == "${target_batch}" ]]
            then
                target_well_rows+=($row)
            fi
        done
    
        batch_file_list=${target_array[@]: ${target_well_rows[0]}:${#target_well_rows[@]} }
    
        num_files_missing=$(check_filepaths_in_assay ${batch_file_list[@]} | wc -l)

        if [[ ${num_files_missing} > 0 ]]
        then
            batches_to_rerun+=(${target_batch})
            echo -e "${target_batch} \t ${num_files_missing}"
        fi
    done 
    
    if [[ ${#batches_to_rerun[@]} > 0 ]]
    then
        echo "batches to re-run:"
        echo "${batches_to_rerun[*]}"        
    fi
}

batchnum=($(query_metadat "batchnum"))

nwells=${#batchnum[@]}
nbatches=${batchnum[-1]}



# apply checks for A05a output -------------------------------------------------

echo "-----------------------------------------------------------------"
echo "A. printing number of missing .bam files missing (by batch)... "
echo "-----------------------------------------------------------------"

bam_starfilt_pe=($(query_metadat "A05c_bam_starfilt_PE"))
bam_starfilt_se1=($(query_metadat "A05c_bam_starfilt_SE1"))
bam_starfilt_se2=($(query_metadat "A05c_bam_starfilt_SE2"))

echo -e "\n\n\nchecking PE.Aligned.out.bam ----------------------------------------------------"
echo -e "batchnum\tnum_missing"
check_filepath_by_batch ${bam_starfilt_pe[@]}

echo -e "\n\n\nchecking SE1.Aligned.out.bam ---------------------------------------------------"
echo -e "batchnum\tnum_missing"
check_filepath_by_batch ${bam_starfilt_se1[@]}

echo -e "\n\n\nchecking SE2.Aligned.out.bam ---------------------------------------------------"
echo -e "batchnum\tnum_missing"
check_filepath_by_batch ${bam_starfilt_se2[@]}

echo -e "\n\n\nsuggest re-running and checking sublog output of above batches."


echo -e "\n\n-----------------------------------------------------------------"
echo "B. checking log files for issues."
echo -e "-----------------------------------------------------------------\n"

echo "checking if 'completed' in sublogs/A05a_star* output."
echo "if any filename is printed, the associated batch may have not completed mapping."

grep -c "'A05c_star_filtering' completed" sublogs/A05c_star* | awk -F ":" '$2==0 {print $1}'





echo -e "\n\n'A05d_starfilt_check' completed.\n\n"



echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `
echo " "
