
#!/bin/bash
#$ -cwd
#$ -o sublogs/A06_compile_DNA.$JOB_ID.$TASK_ID
#$ -j y
#$ -l h_rt=6:00:00,h_data=12G
#$ -N A06_compile_DNA
#$ -t 1-6




echo "Job $JOB_ID.$SGE_TASK_ID started on:   " `hostname -s`
echo "Job $JOB_ID.$SGE_TASK_ID started on:   " `date `
echo " "



# environment init ------------------—------------------—-----------------------

. /u/local/Modules/default/init/modules.sh # <--
module load anaconda3 # <--
conda activate snmCTseq # <--

export $(cat snmCT_parameters.env | grep -v '^#' | xargs) # <--



# run each helper script (A06*) ------------------—------------------—----------

# note: in practice these can each be submitted interactively/as its own task,
# as some of these scripts should be much lower resource than others;
# however, this -t 1-6 job parallelization is just for tidyness

echo "metadata script # $SGE_TASK_ID running:"

case $SGE_TASK_ID in

  1)
    echo "python Scripts/A06a_trimming.py"
    python Scripts/A06a_trimming.py
    ;;

  2)
    echo "python Scripts/A06b_DNA_maprate.py"
    python Scripts/A06b_DNA_maprate.py
    ;;

  3)
    echo "python Scripts/A06c_DNA_dedupe.py"
    python Scripts/A06c_DNA_dedupe.py
    ;;

  4)
    echo "python Scripts/A06d_DNA_mCfracs.py"
    python Scripts/A06d_DNA_mCfracs.py
    ;;

  5)
    echo "python Scripts/A06e_DNA_samtools.py"
    python Scripts/A06e_DNA_samtools.py
    ;;

  6)
    echo "python Scripts/A06f_DNA_cov.py"
    python Scripts/A06f_DNA_cov.py
    ;;
    
  *)
    ;;
esac


echo "completed 'A06_compile_DNA_metadata.'"

echo " "
echo "Job $JOB_ID.$SGE_TASK_ID ended on:   " `hostname -s`
echo "Job $JOB_ID.$SGE_TASK_ID ended on:   " `date `
echo " "

